name: Build and Deploy to AKS with Helm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      run: az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/my-app:latest .
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/my-app:latest

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Deploy with Helm
      run: |
        helm upgrade --install my-app ./helm \
          --set image.repository=${{ secrets.REGISTRY_NAME }}.azurecr.io/my-app \
          --set image.tag=latest
