name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        resourceGroupName: sharedsrvrg
        template: ./main.bicep
        parameters: storageAccountName=pocstorage${{ github.run_id }}
